// Auth Actions
export const AUTH_DATA = 'AUTH_DATA'
export const SET_REG_ERROR = 'SET_REG_ERROR'
export const SET_REG_STEP = 'SET_REG_STEP'
export const AUTH_LOADING='AUTH_LOADING'

//Order Actions
export const ORDER_LISTS='ORDER_LISTS'
export const ORDER_DETAILS='ORDER_DETAILS'
export const ORDER_LOADING='ORDER_LOADING'
export const ORDER_STATUS='ORDER_STATUS'
export const ORDER_PRODUCTS='ORDER_PRODUCTS'
export const ORDER_DADDRESS='ORDER_DADDRESS'
export const ORDER_IADDRESS='ORDER_IADDRESS'
export const ORDER_COUNTS = 'ORDER_COUNTS'
export const WIDGET_ORDER_COUNTS = 'WIDGET_ORDER_COUNTS'
export const WIDGET_ORDER_LISTS = 'WIDGET_ORDER_LISTS'
export const ORDER_STATUS_WITH_COUNT='ORDER_STATUS_WITH_COUNT'
export const ORDERS_SCHEDULE='ORDERS_SCHEDULE'

//Address Actions
export const SUPPLIER_ADDRESS='SUPPLIER_ADDRESS'
export const ADDRESS_LOADING='ADDRESS_LOADING'
export const ADDRESS_STATES='ADDRESS_STATES'

//Settings Actions
export const GET_CUSTOMER_LOGO_SUCCESS='GET_CUSTOMER_LOGO_SUCCESS'
export const DR_PREFIX='DR_PREFIX'
export const DR_NUMBER='DR_NUMBER'
export const SETTINGS_LOADING='SETTINGS_LOADING'

//sales Actions
export const TOP_CUSTOMERS='TOP_CUSTOMERS'
export const MONTHLY_SALES='MONTHLY_SALES'
export const SALES_LOADING='SALES_LOADING'
export const TOP_CUSTOMERS_LOADING='TOP_CUSTOMERS_LOADING'
export const MONTHLY_SALES_LOADING='MONTHLY_SALES_LOADING'
export const TOP_SOLD_PRODUCTS='TOP_SOLD_PRODUCTS'
export const TOP_PRODUCTS_LOADING='TOP_PRODUCTS_LOADING'
export const DASHBOARD_KPI='DASHBOARD_KPI'
//quotation Actions
export const QUOTATIONS_REQUESTS_LISTS = 'QUOTATIONS_REQUESTS_LISTS'
export const QUOTATIONS_LOADING = 'QUOTATIONS_LOADING'
export const CLEAR_QUOTATIONS='CLEAR_QUOTATIONS'
export const QUOTATIONS_REQUESTS_LISTS_COUNT = 'QUOTATIONS_REQUESTS_LISTS_COUNT'
export const ACCEPTED_CUSTOMER='ACCEPTED_CUSTOMER'
export const ACCEPTED_CUSTOMER_COUNT='ACCEPTED_CUSTOMER_COUNT'

//Customer Actions
export const ALL_CUSTOMERS = 'ALL_CUSTOMERS'

//Catalog Actions
export const CONTRACT_LISTS = 'CONTRACT_LISTS'
export const CONTRACT_COUNT = 'CONTRACT_COUNT'
export const CATALOG_LOADING = 'CATALOG_LOADING'
export const PRODUCT_LIST = 'PRODUCT_LIST'
export const PRODUCT_COUNT = 'PRODUCT_COUNT'

//Common Actions
export const SELECTED_CATEGORY='SELECTED_CATEGORY'
export const SELECTED_CITY='SELECTED_CITY'
export const ALL_STATE='ALL_STATE'
export const MY_BUYERS='MY_BUYERS'

//Inventory Actions
export const INVENTORY_LOADING='INVENTORY_LOADING'
export const INVENTORY_COUNTS='INVENTORY_COUNTS'
export const INVENTORY_LISTS='INVENTORY_LISTS'
export const PARENT_CHILD_STRUCTURE='PARENT_CHILD_STRUCTURE'
export const INVENTORY_PRODUCTS='INVENTORY_PRODUCTS'
export const DEFAULT_INVENTORY='DEFAULT_INVENTORY'