

INSERT INTO `kob_order_state_lang` (`id_order_state`, `id_lang`, `name`, `template`) VALUES
(32, 1, 'Order Processing Held', 'ORDER_PROCESSING_HELD'),
(32, 2, 'Order Processing Held', 'account'),
(32, 3, 'Order Processing Held', 'account'),
(32, 4, 'Order Processing Held', 'account'),
(32, 5, 'Order Processing Held', 'account'),
(33, 1, 'Packed and Ready to be shipped', ''),
(33, 2, 'Packed and Ready to be shipped', ''),
(33, 3, 'Packed and Ready to be shipped', ''),
(33, 4, 'Packed and Ready to be shipped', ''),
(33, 5, 'Packed and Ready to be shipped', ''),
(34, 1, 'Offline invoice generated', ''),
(34, 2, 'Offline invoice generated', ''),
(34, 3, 'Offline invoice generated', ''),
(34, 4, 'Offline invoice generated', ''),
(34, 5, 'Offline invoice generated', ''),
(35, 1, 'Pending Payment', ''),
(35, 2, 'Pending Payment', ''),
(35, 3, 'Pending Payment', ''),
(35, 4, 'Pending Payment', ''),
(35, 5, 'Pending Payment', ''),
(36, 1, 'Payment recieved', ''),
(36, 2, 'Payment recieved', ''),
(36, 3, 'Payment recieved', ''),
(36, 4, 'Payment recieved', ''),
(36, 5, 'Payment recieved', ''),
(37, 1, 'Pending Invoice', ''),
(37, 2, 'Pending Invoice', ''),
(37, 3, 'Pending Invoice', ''),
(37, 4, 'Pending Invoice', ''),
(37, 5, 'Pending Invoice', ''),
(38, 1, 'Order Completed', ''),
(38, 2, 'Order Completed', ''),
(38, 3, 'Order Completed', ''),
(38, 4, 'Order Completed', ''),
(38, 5, 'Order Completed', '');
