// Dashboard container
export const GET_ORDER_HISTORY_SUCCESS = 'GET_ORDER_HISTORY_SUCCESS'
export const GET_APPROVALS_HOME_SUCCESS = 'GET_APPROVALS_HOME_SUCCESS'
export const GET_RM_SUCCESS = 'GET_RM_SUCCESS'
export const GET_TOP4_PRODUCTS_SUCCESS = 'GET_TOP4_PRODUCTS_SUCCESS'
export const GET_TOP_CATEGORY_SUCCESS = 'GET_TOP_CATEGORY_SUCCESS'
export const REQUEST_ORDER_STATUS_DASHBOARD = 'REQUEST_ORDER_STATUS_DASHBOARD'
export const REQUEST_APPROVALS_DASHBOARD = 'REQUEST_APPROVALS_DASHBOARD'
export const REQUEST_RM_DASHBOARD = 'REQUEST_RM_DASHBOARD'
export const REQUEST_TOP4PRODUCTS_DASHBOARD = 'REQUEST_TOP4PRODUCTS_DASHBOARD'
export const REQUEST_TOPCATEGORIES_DASHBOARD = 'REQUEST_TOPCATEGORIES_DASHBOARD'
export const REQUEST_DASHBOARD_WIDGETS = 'REQUEST_DASHBOARD_WIDGETS'
export const GET_ELITE_DEALS = 'GET_ELITE_DEALS'
// Procure/buy container
export const GET_PURCHASE_LIST_SUCCESS = 'GET_PURCHASE_LIST_SUCCESS'
export const GET_PURCHASE_CATEGORIES_SUCCESS = 'GET_PURCHASE_CATEGORIES_SUCCESS'
export const GET_PURCHASE_SUPPLIER_SUCCESS='GET_PURCHASE_SUPPLIER_SUCCESS'
export const GET_PO_PRODUCTS_SUCCESS = 'GET_PO_PRODUCTS_SUCCESS'
export const REQUEST_PURCHASE_LIST = 'REQUEST_PURCHASE_LIST'
export const REQUEST_PURCHASE_CATEGORIES = 'REQUEST_PURCHASE_CATEGORIES'
export const REQUEST_PURCHASE_CATEGORY_PRODUCTS = 'REQUEST_PURCHASE_CATEGORY_PRODUCTS'
export const REQUEST_UPLOAD_PO = 'REQUEST_UPLOAD_PO'
export const RESPONSE_UPLOAD_PO = 'RESPONSE_UPLOAD_PO'
export const REQUEST_SUPPLIER_PRODUCTS='REQUEST_SUPPLIER_PRODUCTS'

// Orders container
export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS'
export const ORDER_COMPLETE_SUCCESS = 'ORDER_COMPLETE_SUCCESS'
export const GET_ORDER_BY_ID = 'GET_ORDER_BY_ID'
export const GET_ORDER_PAGE_DATA_SUCCESS = 'GET_ORDER_PAGE_DATA_SUCCESS'
export const REQUEST_ORDERS = 'REQUEST_ORDERS'
export const REQUEST_ORDER_COMPLETE = 'REQUEST_ORDER_COMPLETE'
export const REQUEST_UNIQUE_ORDER = 'REQUEST_UNIQUE_ORDER'
export const GET_ORDER_PAYMENT_METHOD = 'GET_ORDER_PAYMENT_METHOD'
export const ORDER_PROCESS_STATUS = 'ORDER_PROCESS_STATUS';
export const LOADING='LOADING'
export const ORDER_DETAIL_LOADING = 'ORDER_DETAIL_LOADING'
export const ORDER_LIST_LOADING = 'ORDER_LIST_LOADING'
export const SET_ORDER_DETAILS='SET_ORDER_DETAILS'
export const CLEAN_ORDER_DETAILS='CLEAN_ORDER_DETAILS'
export const ORDER_DETAILS='ORDER_DETAILS'
export const ORDER_DELIVERY_ADDRESS='ORDER_DELIVERY_ADDRESS'
export const ORDER_INVOICE_ADDRESS='ORDER_INVOICE_ADDRESS'
export const ORDER_PRODUCT_DETAILS='ORDER_PRODUCT_DETAILS'
export const ORDER_ORDER_STATUS='ORDER_ORDER_STATUS'
export const ORDER_SCHEDULED_PRODUCT='ORDER_SCHEDULED_PRODUCT'
export const ORDER_CANCELED_PRODUCT='ORDER_CANCELED_PRODUCT'


// Reports container
export const GET_HISTORY_SUCCESS = 'GET_HISTORY_SUCCESS'
export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS'
export const MAP_LOCATION_CAPTURED = 'MAP_LOCATION_CAPTURED'
export const GET_LOCATIONS_SUCCESS = 'GET_LOCATIONS_SUCCESS'
export const CUSTOMER_STATES_FOR_REPORTS = 'CUSTOMER_STATES_FOR_REPORTS'

//Pending Payments
export const REQUEST_PENDING_PAYMENT = 'REQUEST_PENDING_PAYMENT'
export const GET_PENDING_PAYMENT = 'GET_PENDING_PAYMENT'

// Invoices container
export const GET_INVOICES_SUCCESS = 'GET_INVOICES_SUCCESS'
export const GET_DR_SUCCESS = 'GET_DR_SUCCESS'
export const REQUEST_INVOICE = 'REQUEST_INVOICE'
export const REQUEST_DELIVERY_RECIEPT = 'REQUEST_DELIVERY_RECIEPT'
export const REQUEST_HISTORY_CHART = 'REQUEST_HISTORY_CHART'
export const REQUEST_CATEGORY_CHART = 'REQUEST_CATEGORY_CHART'
export const REQUEST_LOCATIONS_CHART = 'REQUEST_LOCATIONS_CHART'

// Approvals container
export const GET_APPROVALS_SUCCESS = 'GET_APPROVALS_SUCCESS'
export const REQUEST_APPROVALS = 'REQUEST_APPROVALS'

/** Cart **/
export const REQUEST_CART = 'REQUEST_CART'
export const REQUEST_CART_SUMMARY = 'REQUEST_CART_SUMMARY'
export const GET_CART_SUCCESS = 'GET_CART_SUCCESS'
export const GET_CART_SUMMARY = 'GET_CART_SUMMARY'
export const GET_LOYALTY_COUNT_SUCCESS = 'GET_LOYALTY_COUNT_SUCCESS'
export const GET_LOYALTY_SUCCESS = 'GET_LOYALTY_SUCCESS'
export const REQUEST_ADD_PRODUCT = 'REQUEST_ADD_PRODUCT'
export const RESPONSE_ADD_PRODUCT = 'RESPONSE_ADD_PRODUCT'

/** Address **/
export const GET_ADDRESS_SUCCESS = 'GET_ADDRESS_SUCCESS'
export const GET_UNIQUE_ADDRESS_SUCCESS = 'GET_UNIQUE_ADDRESS_SUCCESS'
export const GET_STATE_SUCCESS = 'GET_STATE_SUCCESS'
export const GET_ORDER_ID_PAYMENT = 'GET_ORDER_ID_PAYMENT'
export const GET_BILLING_ADDRESS_SUCCESS = 'GET_BILLING_ADDRESS_SUCCESS'
export const REQUEST_UNIQUE_ADDRESS = 'REQUEST_UNIQUE_ADDRESS'
export const REQUEST_ADDRESS_LIST = 'REQUEST_ADDRESS_LIST'
export const REQUEST_DEALS = 'REQUEST_DEALS'
export const ALL_STATES_RESPONSE = 'ALL_STATES_RESPONSE'
export const PURCHASE_ORDERS_BY_ADDRESS = 'PURCHASE_ORDERS_BY_ADDRESS'

/** Order confirmation **/
export const GET_VOUCHERS_SUCCESS = 'GET_VOUCHERS_SUCCESS'
export const GET_COMPANIES_ALSO_BOUGHT_SUCCESS = 'GET_COMPANIES_ALSO_BOUGHT_SUCCESS'
export const GET_PAYMENT_SUCCESS = 'GET_PAYMENT_SUCCESS'
export const REQUEST_PAYMENT_MODES = 'REQUEST_PAYMENT_MODES'

/** Deals **/
export const GET_DEALS_SUCCESS = 'GET_DEALS_SUCCESS'

/** Search **/
export const PRODUCT_DATA = 'PRODUCT_DATA'
export const SEARCH_RESULTS = 'SEARCH_RESULTS'
export const SEARCH_FILTER_RESULTS = 'SEARCH_FILTER_RESULTS'


/** Widgets **/
export const GET_WIDGETS_SUCCESS = 'GET_WIDGETS_SUCCESS'
export const GET_WIDGET_STATUS = 'GET_WIDGET_STATUS'
export const GET_DASHBOARD_WIDGET_SUCCESS = 'GET_DASHBOARD_WIDGET_SUCCESS'
export const UNIQUE_WIDGET_RESPONSE = 'UNIQUE_WIDGET_RESPONSE'

/** Hotel API **/
export const GET_HOTELS_SUCCESS = 'GET_HOTELS_SUCCESS'

/** Notifications **/
export const GET_TOPBAR_NOTIFICATIONS_SUCCESS = 'GET_TOPBAR_NOTIFICATIONS_SUCCESS'
export const GET_NOTIFICATIONS_SUCCESS = 'GET_NOTIFICATIONS_SUCCESS'

/** API **/
export const GET_SKYSCANNER_FLIGHTS_SUCCESS = 'GET_SKYSCANNER_FLIGHTS_SUCCESS'

/** Help/FAQs **/
export const HELP_FAQS_RESPONSE = 'HELP_FAQS_RESPONSE'

/** Settings **/
export const GET_CUSTOMER_LOGO_SUCCESS = 'GET_CUSTOMER_LOGO_SUCCESS'
export const GET_PO_OPTIONS_SUCCESS = 'GET_PO_OPTIONS_SUCCESS'

/**Filters / Categories/Brand/Search**/

export const GET_CATEGORY_PRODUCTS_SUCCESS = 'GET_CATEGORY_PRODUCTS_SUCCESS'
export const GET_CATEGORY_PRODUCTS_WITH_FILTERS = 'GET_CATEGORY_PRODUCTS_WITH_FILTERS'
export const GET_CATEGORY_PRODUCTS_WITH_FILTERS_VALUES = 'GET_CATEGORY_PRODUCTS_WITH_FILTERS_VALUES'
export const GET_BRAND_PRODUCTS_WITH_FILTERS = 'GET_BRAND_PRODUCTS_WITH_FILTERS'
export const GET_BRAND_PRODUCTS_WITH_FILTERS_VALUES = 'GET_BRAND_PRODUCTS_WITH_FILTERS_VALUES'

/* Budget control */
export const PURCHASE_ORDER_BUDGET = 'PURCHASE_ORDER_BUDGET'
export const BUDGET_INSTALLED = 'BUDGET_INSTALLED'
export const REQUEST_PO_DASHBOARD = 'REQUEST_PO_DASHBOARD'
export const GET_PO_DASHBOARD_SUCCESS = 'GET_PO_DASHBOARD_SUCCESS'

/* Company Information */
export const COMPANY_INFO = 'COMPANY_INFO'
export const SEARCH_WIDGET_STATUS = 'SEARCH_WIDGET_STATUS'

/* Header */
export const CONTROLLED_MEGAMENU = 'CONTROLLED_MEGAMENU'
export const GET_FC_SUCCESS = 'GET_FC_SUCCESS'

/* Search */
export const ALL_AVAILABLE_RESULTS = 'ALL_AVAILABLE_RESULTS'
export const CLEAR_RESULTS='CLEAR_RESULTS'
export const ALL_CATEGORY_RESULTS = 'ALL_CATEGORY_RESULTS'
export const ALL_BRAND_RESULTS = 'ALL_BRAND_RESULTS'
export const UPDATE_CATEGORY_RESULTS = 'UPDATE_CATEGORY_RESULTS'
export const UPDATE_BRAND_RESULTS = 'UPDATE_BRAND_RESULTS'
export const MAX_PRICE = 'MAX_PRICE'
export const ALL_ZONES = 'ALL_ZONES'
export const SEARCHING = 'SEARCHING'
export const GOT_IT = 'GOT_IT'
export const SEARCH_DETAILS='SEARCH_DETAILS'
export const PRODUCT_DETAILS = 'PRODUCT_DETAILS'
export const SUPPLIER_DETAILS='SUPPLIER_DETAILS'
export const SUPPLIER_FETCHING='SUPPLIER_FETCHING'
export const CLEAR_FILTERS='CLEAR_FILTERS'

//quotation Actions
export const QUOTATIONS_REQUESTS_LISTS = 'QUOTATIONS_REQUESTS_LISTS'
export const QUOTATIONS_LOADING = 'QUOTATIONS_LOADING'
export const CLEAR_QUOTATIONS='CLEAR_QUOTATIONS'
export const QUOTATIONS_REQUESTS_LISTS_COUNT = 'QUOTATIONS_REQUESTS_LISTS_COUNT'
export const QUOTATIONS_REQUESTS_DETAILS = 'QUOTATIONS_REQUESTS_DETAILS'
export const QUOTATIONS_RESPOND_SUPPLIERS = 'QUOTATIONS_RESPOND_SUPPLIERS'

//common Actions
export const SELECTED_CITIES = 'SELECTED_CITIES'
export const SELECTED_CATEGORY = 'SELECTED_CATEGORY'